from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
from sqlalchemy import func
import models
from database import engine, get_db
from pydantic import BaseModel
import google.generativeai as genai
from fastapi.middleware.cors import CORSMiddleware

import os
from dotenv import load_dotenv

# This loads the variables from your .env file into your system
load_dotenv()

# Get the key from the environment
api_key = os.getenv("GEMINI_API_KEY")




# Create the database tables if they don't exist
models.Base.metadata.create_all(bind=engine)

app = FastAPI()
origins = [
    "http://localhost:8080",      # For when you test locally
    "https://lovable.dev",        # Allow Lovable's editor
    "*"                            # The 'Wildcard' - allows ANY site to talk to you. 
                                   # Use "*" for now to make testing easy!
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],           # Allows GET, POST, DELETE, etc.
    allow_headers=["*"],           # Allows all security headers
)

# Pydantic schema for the API request
class StudentCreate(BaseModel):
    name: str
    gpa: float

@app.get("/")
def home():
    return {"message": "Welcome to Inam's SQL-powered API"}

@app.get("/deans-list")
def get_deans_list(db: Session = Depends(get_db)):
    # This is the "ORM" way to say: SELECT * FROM students WHERE gpa > 3.5
    honors = db.query(models.StudentDB).filter(models.StudentDB.gpa > 3.5).all()
    return {"dean_list": honors}

@app.post("/add-student")
def add_student(student: StudentCreate, db: Session = Depends(get_db)):
    # 1. Create an instance of the Database Model
    new_student = models.StudentDB(name=student.name, gpa=student.gpa)
    
    # 2. Tell the database to add and save it
    db.add(new_student)
    db.commit()
    db.refresh(new_student) # This gets the 'id' generated by the DB
    
    return {"message": f"Student {new_student.name} added with ID {new_student.id}"}

@app.delete("/delete-student/{student_id}")
def delete_student(student_id: int, db: Session = Depends(get_db)):
    # 1. Find the student by ID
    student = db.query(models.StudentDB).filter(models.StudentDB.id == student_id).first()
    
    # 2. If student doesn't exist, throw an error
    if not student:
        raise HTTPException(status_code=404, detail="Student not found")
    
    # 3. Delete and save changes
    db.delete(student)
    db.commit()
    
    return {"message": f"Student with ID {student_id} deleted successfully"}


@app.get("/search")
def search_students(name: str = None, db: Session = Depends(get_db)):
    """
    Finds students by name.
    Example: http://127.0.0.1:8000/search?name=Inam
    """
    query = db.query(models.StudentDB)
    if name:
        # This looks for any name that 'contains' the text you typed
        query = query.filter(models.StudentDB.name.contains(name))
    
    return query.all()

@app.get("/stats")
def get_student_stats(db: Session = Depends(get_db)):
    """
    Provides a quick analysis of all students in the database.
    """
    total_students = db.query(models.StudentDB).count()
    
    # We use 'func' here to let the database calculate the average and max
    average_gpa = db.query(func.avg(models.StudentDB.gpa)).scalar()
    highest_gpa = db.query(func.max(models.StudentDB.gpa)).scalar()
    
    return {
        "total_count": total_students,
        "average_gpa": round(average_gpa, 2) if average_gpa else 0,
        "topper_gpa": highest_gpa
    }


# Configure your AI (Replace 'YOUR_API_KEY' with your real key)
# Configure the existing library
def get_model():
    # This force-checks Render's Environment Variables every time
    key = os.environ.get("GEMINI_API_KEY")
    if not key:
        # Fallback for local testing
        key = api_key 
    
    genai.configure(api_key=key)
    return genai.GenerativeModel('models/gemini-2.0-flash')
@app.get("/ai-advice/{student_id}")
def get_ai_advice(student_id: int, db: Session = Depends(get_db)):
    student = db.query(models.StudentDB).filter(models.StudentDB.id == student_id).first()
    
    if not student:
        raise HTTPException(status_code=404, detail="Student not found")

    try:
        current_model = get_model() 
        
        prompt = f"A student named {student.name} has a GPA of {student.gpa}. Give 2 lines of encouraging advice."
        response = current_model.generate_content(prompt)
        
        return {
            "student_name": student.name,
            "ai_advice": response.text
        }
    except Exception as e:
        if "429" in str(e):
            return {"message": "The AI is busy thinking for other students. Please wait 1 minute and try again!"}
        
        print(f"AI ERROR: {e}")
        return {"error": "AI Connection Issue", "details": str(e)}
    